# tox Configuration

requires = ["tox>=4"]
env_list = ["3.11"]

[env_run_base]
description = "Run Unit Test"
deps = [
  "pytest>=9.0",
  "pytest-asyncio",
  "pytest-cov",
  "pytest-mock",
]
commands = [["pytest", "-m", "mock"]]
